
GET http://localhost:8080/api/company/1
Content-Type: application/json

###
GET http://localhost:8080/api/company
Content-Type: application/json

###
POST http://localhost:8080/api/company/register
Content-Type: application/json

{
    "username": "nandu12345",
    "password": "1234",
    "companyName": "Example Co",
    "companyOwnerName": "Owner Name",
    "location": "City",
    "address": "123 Street",
    "phoneNumber": "1234567890"
}

### Login request
POST http://localhost:8080/api/auth/login?username=testuser12345&password=password123
Content-Type: application/json

{
  "username": "testuser123",
  "password": "password123"
}
